import {useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db,createSale} from '../db';
import type {Item,Variant,Sale} from '../types';
import {Search,Minus,Plus,ShoppingBag,X,Check} from 'lucide-react';
import {Receipt} from './Receipt';

type Cart={item:Item;variant:Variant;quantity:number;price:number};
export function Sell(){
  const [q,setQ]=useState(''),[cart,setCart]=useState<Cart[]>([]),[receipt,setReceipt]=useState<Sale|null>(null),[customerName,setCustomerName]=useState(''),[discount,setDiscount]=useState(0),[busy,setBusy]=useState(false);
  const items=useLiveQuery(()=>db.items.filter(i=>!i.deletedAt).toArray())??[];
  const results=items.filter(i=>i.modelNumber.toLowerCase().includes(q.toLowerCase())||i.variants.some(v=>v.color.toLowerCase().includes(q.toLowerCase())));
  const add=(item:Item,v:Variant)=>setCart(c=>{const n=c.find(x=>x.variant.id===v.id);return n?c.map(x=>x===n?{...x,quantity:Math.min(x.quantity+1,v.stockQuantity)}:x):[...c,{item,variant:v,quantity:1,price:item.price}]});
  const subtotal=cart.reduce((s,x)=>s+x.quantity*x.price,0),discountAmount=subtotal*discount/100,total=Math.round((subtotal-discountAmount)*100)/100;
  const complete=async()=>{setBusy(true);try{const sale=await createSale(cart.map(x=>({variant:x.variant,item:x.item,quantity:x.quantity,price:x.price})),{customerName,discountPercentage:discount});sale.items=sale.items.map(l=>({...l,itemVariant:{...cart.find(x=>x.variant.id===l.itemVariantId)!.variant,item:cart.find(x=>x.variant.id===l.itemVariantId)!.item}}));setCart([]);setCustomerName('');setDiscount(0);setReceipt(sale)}finally{setBusy(false)}};
  if(receipt)return <Receipt sale={receipt} onClose={()=>setReceipt(null)}/>;
  return <div className="sell-layout"><section><div className="section-head compact"><div><p className="eyebrow">NEW TRANSACTION</p><h2>Select a dress</h2></div></div><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Model or colour…"/></div><div className="sell-list">{results.map(item=><article key={item.id}><div className="model-badge">{item.modelNumber.slice(0,2)}</div><div><small>MODEL</small><h3>{item.modelNumber}</h3><strong>{item.price.toLocaleString()} EGP</strong></div><div className="variant-buttons">{item.variants.filter(v=>v.stockQuantity>0).map(v=><button key={v.id} onClick={()=>add(item,v)}><span>{v.color}</span><small>{v.stockQuantity} left</small><Plus size={16}/></button>)}</div></article>)}</div></section><aside className="basket"><header><ShoppingBag/><div><p className="eyebrow">CURRENT SALE</p><h2>Your basket</h2></div><span>{cart.reduce((s,x)=>s+x.quantity,0)}</span></header>{!cart.length?<div className="basket-empty"><ShoppingBag/><p>Select a colour to begin the sale.</p></div>:<div className="basket-lines">{cart.map((x,n)=><article key={x.variant.id}><div><b>{x.item.modelNumber}</b><span>{x.variant.color}</span></div><div className="quantity"><button onClick={()=>setCart(c=>c.map((z,i)=>i===n?{...z,quantity:Math.max(1,z.quantity-1)}:z))}><Minus/></button><b>{x.quantity}</b><button onClick={()=>setCart(c=>c.map((z,i)=>i===n?{...z,quantity:Math.min(z.quantity+1,z.variant.stockQuantity)}:z))}><Plus/></button></div><label><input type="number" min="0" value={x.price} onChange={e=>setCart(c=>c.map((z,i)=>i===n?{...z,price:Number(e.target.value)}:z))}/> EGP</label><button className="remove" onClick={()=>setCart(c=>c.filter((_,i)=>i!==n))}><X/></button></article>)}</div>}<div className="checkout-details"><label>Client name<input value={customerName} maxLength={120} onChange={e=>setCustomerName(e.target.value)} placeholder="Optional client name"/></label><label>Discount percentage<div className="discount-input"><input type="number" min="0" max="100" step="0.5" value={discount} onChange={e=>setDiscount(Math.min(100,Math.max(0,Number(e.target.value))))}/><span>%</span></div></label></div><footer>{discount>0&&<><div className="checkout-row"><span>Subtotal</span><b>{subtotal.toLocaleString()} EGP</b></div><div className="checkout-row discount"><span>Discount ({discount}%)</span><b>− {discountAmount.toLocaleString()} EGP</b></div></>}<div><span>Total</span><strong>{total.toLocaleString()} <small>EGP</small></strong></div><button className="primary sale-button" disabled={!cart.length||busy} onClick={complete}><Check/> {busy?'Completing…':'Complete sale'}</button></footer></aside></div>
}